### ISSUE TITLE
Schema designer not showing tables etc.

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#716] opened 2015-09-16 15:51 UTC
To reproduce, try to view a database structure in the Dev version of ORDS. The gridded background appears, but not the tables, relationships, or the toolbar. This is happening for me in both Chrome and Firefox.

**Comment by thestoat** [comment] 2015-10-01 09:12
I suspect this would be one for Scott ...

**Comment by scottbw** [comment] 2015-10-06 15:27
This is caused by bug #720

**Comment by thestoat** [comment] 2015-10-07 14:19
This should now be ok

**Comment by scottbw** [comment] 2015-10-07 15:14
Fixed as result of closing #720

**Closed as completed by scottbw** 2015-10-07 15:14 UTC
Labels: Type-Defect, Priority-Critical
