### ISSUE TITLE
Stack trace error when trying to access database pages in Dev

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#728] opened 2015-10-19 09:01 UTC
Since this morning I seem to be unable to get to any database pages in Dev - I click on a database name in a project page and get the following error. My Sherlock-like skills of deduction suggest it may be related to the billing component again...

HTTP Status 500 - Unable to compile class for JSP: An error occurred at line: 94 in the jsp file: /database.jsp Project.showBilling cannot be resolved 91: <tr><th><%= lang.getString("creationdate") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getCreationDate())%></td></tr> 92: <tr><th><%= lang.getString("datasources") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataSources())%></td></tr> 93: <tr><th><%= lang.getString("datagathering") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataGatheringProcess())%></td></tr> 94: <% if (Project.showBilling) { %> 95: <tr><th><%= lang.getString("datainterfacename") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataInterfaceName())%></td></tr> 96: <% } %> 97: Stacktrace:

type Exception report

message Unable to compile class for JSP: An error occurred at line: 94 in the jsp file: /database.jsp Project.showBilling cannot be resolved 91: <tr><th><%= lang.getString("creationdate") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getCreationDate())%></td></tr> 92: <tr><th><%= lang.getString("datasources") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataSources())%></td></tr> 93: <tr><th><%= lang.getString("datagathering") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataGatheringProcess())%></td></tr> 94: <% if (Project.showBilling) { %> 95: <tr><th><%= lang.getString("datainterfacename") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataInterfaceName())%></td></tr> 96: <% } %> 97: Stacktrace:

description The server encountered an internal error (Unable to compile class for JSP: An error occurred at line: 94 in the jsp file: /database.jsp Project.showBilling cannot be resolved 91: <tr><th><%= lang.getString("creationdate") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getCreationDate())%></td></tr> 92: <tr><th><%= lang.getString("datasources") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataSources())%></td></tr> 93: <tr><th><%= lang.getString("datagathering") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataGatheringProcess())%></td></tr> 94: <% if (Project.showBilling) { %> 95: <tr><th><%= lang.getString("datainterfacename") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataInterfaceName())%></td></tr> 96: <% } %> 97: Stacktrace:) that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 94 in the jsp file: /database.jsp
Project.showBilling cannot be resolved
91:                         <tr><th><%= lang.getString("creationdate") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getCreationDate())%></td></tr>
92:                         <tr><th><%= lang.getString("datasources") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataSources())%></td></tr>
93:                         <tr><th><%= lang.getString("datagathering") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataGatheringProcess())%></td></tr>
94:                         <% if (Project.showBilling) { %>
95:                         <tr><th><%= lang.getString("datainterfacename") %></th><td><%=StringEscapeUtils.escapeHtml4(database.getDataInterfaceName())%></td></tr>
96:                         <% } %>
97:                     

Stacktrace:
    org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
    org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:331)
    org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:469)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:378)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:646)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.28 logs.

**Comment by scottbw** [comment] 2015-10-19 09:13
Another issue caused by the tendrils of Billing reaching into odd places. I've removed the reference and retested locally - should be fixed now.

**Closed as completed** 2015-10-20 14:17 UTC
Labels: bug, Priority-Critical, Scott Wilson
